---
- name: Check packer version
  shell: "packer --version 2>&1 | grep {{packer_version}}"
  failed_when: false
  changed_when: false
  register: packer_versions_match

- include: download.yml
  when: packer_versions_match.rc != 0

- name: Install unzip to unarchive packer
  apt:
    name: unzip
    state: present

- name: Unarchive packer archive
  unarchive:
    src: /tmp/packer-{{ packer_version }}.zip
    dest: "/usr/local/bin"
    copy: no
  when: packer_versions_match.rc != 0
...
